### ISSUE TITLE
Broken references deserialization

### ISSUE THREAD

**Issue by ondrasvoboda** [ExtendedXmlSerializer/home#407] opened 2020-06-22 11:18 UTC
Hi,
after updating to the latest version 3.2.0 I'm unable to deserialize correctly XML created with .EnableReferences() option.

Fragment of my XML file:
```
    <ns1:Lookuptable xmlns:ns32="clr-namespace:MA.App.Model.Dto.Lookuptables;assembly=MA" exs:arguments="ns32:PathogenDto">
        <Models>
            <Capacity>64</Capacity>
            <ns2:Pathogen>
                <ScientificName>Phellinus igniarius</ScientificName>
                <LocalizedName>Phellinus igniarius</LocalizedName>
                <PathogenType exs:member="" exs:identity="1">
                    <Code>f</Code>
                    <Description>Fungus</Description>
                </PathogenType>
            </ns2:Pathogen>
            <ns2:Pathogen>
                <ScientificName>Pholiota destruens</ScientificName>
                <LocalizedName>Pholiota destruens</LocalizedName>
                <PathogenType exs:member="" exs:reference="1" />
            </ns2:Pathogen>
    </ns1:Lookuptable>
    <ns1:Lookuptable xmlns:ns36="clr-namespace:MA.App.Model.Dto.Lookuptables;assembly=MA" exs:arguments="ns36:PathogenTypeDto">
        <Models>
            <ns2:PathogenType exs:reference="1" />
        </Models>
    </ns1:Lookuptable>
```

After deserialization I get PathogenType with Code and Description null, instead of "f" and "Fungus".  It works in 3.1.4. I've seen some changes regarding references in the last version, so am I missing something or is it a bug?

Thanks!

**Comment by Mike-E-wins** [comment] 2020-06-22 13:11
Boo... I was afraid of something like this.  Thank you for taking the time to report. 
 Yes, we did do some work with `3.2.0` around references to change how references work in the case of attributes.  Although, I am not sure why that would impact you as you do not seem to be using attributes and everything is an element.

Is the above a list?  I will attempt to create the object graph and see if I can reproduce this for you.  Apologies for breaking your code. 😞  Please use `3.1.4` until we figure this out.

**Comment by ondrasvoboda** [comment] 2020-06-22 13:20
Yes, it is a list of lookuptables and each has list of values in Models property. A value sometimes reference value from another lookup table - like in this case Pathogen reference PathogenType which is another lookuptable.
Thanks for looking into it.

**Comment by Mike-E-wins** [comment] 2020-06-22 13:24
OK cool thank you for the context, @ondrasvoboda.  To be sure, your referenced XML above does not have a closing `</Models>` tag so want to be sure that's due to removing additional data and not a malformed document.

**Comment by ondrasvoboda** [comment] 2020-06-22 13:26
Yes, that's due to removing additional data.

**Comment by Mike-E-wins** [comment] 2020-06-22 13:57
Alright @ondrasvoboda unfortunately I am not having any luck reproducing this.  I am eyeballing the model so there might be something fundamental that I am overlooking here.  This is what I have and seems to be passing OK:

https://github.com/ExtendedXmlSerializer/home/blob/3d0c314e395e73708444c65cd4b4bc99f0d35227/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue407Tests.cs#L12-L67

Is there anything that sticks out at you that I am not considering?

**Comment by Mike-E-wins** [comment] 2020-06-22 14:11
Boom... figured it out.  It's our good friend the `member=""` hack.  This does not look promising but I will look into this.  Hang tight with `3.1.4` in the meantime.

**Comment by Mike-E-wins** [comment] 2020-06-22 14:27
Alright @ondrasvoboda check out the instructions here:
https://github.com/ExtendedXmlSerializer/home/pull/408#issuecomment-647553497

And see if that treats you better.  If it does, I will release this to NuGet ASAP since this will no doubt break others.

**Comment by ondrasvoboda** [comment] 2020-06-22 14:42
Works great, thanks!

**Closed** 2020-06-22 14:45 UTC
Labels: bug

**Comment by Mike-E-wins** [comment] 2020-06-22 14:59
Awesome!  Good news is that as easier than I expected, but bad news is that it involved adding another boolean check to the code which makes it feel hackier.  I am very much hoping `exs:member=""` doesn't make any more appearances, in any case.

Anyways, v3.2.1 is here:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Not complaining about that version number, either! 😆
