### ISSUE TITLE
ArgumentNullException when Deserializing a Class in a Collection with an Interface and Migration

### ISSUE THREAD

**Issue by imperiobadgo** [ExtendedXmlSerializer/home#517] opened 2021-03-26 09:04 UTC
Hello everyone, I have found a problem with Migrations again. This time it seems to be a very special scenario involving interfaces and different namespaces. My Issue Example:

```
using ExtendedXmlSerializer.Configuration;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Xml.Linq;

namespace ExtendedXmlSerializer.Tests.Performance
{
  class MigrationInterfaceNamespaceIssue
  {
    public static void Run()
    {
      var asset = new FirstNameSpace.ItemContainer();
      for (int i = 0; i < 1; i++)
      {
        var subject = new FirstNameSpace.Class1();
        subject.obj = new SecondNameSpace.Class2();
        asset.Items.Add(subject);
      }

      IConfigurationContainer config = new ConfigurationContainer();
      config.Type<FirstNameSpace.ItemContainer>().AddMigration(new EmptyMigration());
      var serializer = config.Create();

      var output = serializer.Serialize(asset);

      // Exception is thrown: ArgumentNullException
      var loaded = serializer.Deserialize<FirstNameSpace.ItemContainer>(output);
    }

    public class EmptyMigration : IEnumerable<Action<XElement>>
    {
      public IEnumerator<Action<XElement>> GetEnumerator()
      {
        yield return x => { }; //Do nothing
      }

      IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

    }

  }

  namespace FirstNameSpace
  {
    class ItemContainer
    {

      public List<Class1> Items { get; set; } = new List<Class1>();

    }

    class Class1
    {

      public Interface1 obj { get; set; }
    }

    interface Interface1 { }

  }

  namespace SecondNameSpace
  {
    class Class2 : FirstNameSpace.Interface1 { }
  }
}
```
I get following Stacktrace:

```
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ExtendedXmlSerializer.Core.Sources.CacheBase`2.Get(TKey key) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\Core\Sources\CacheBase.cs:line 34
   at ExtendedXmlSerializer.ContentModel.Identification.IdentityStore.Get(String name, String identifier) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Identification\IdentityStore.cs:line 10
   at ExtendedXmlSerializer.ExtensionModel.Xml.IdentityMapper.Get(String name, String identifier) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ExtensionModel\Xml\IdentityMapper.cs:line 17
   at ExtendedXmlSerializer.ContentModel.Reflection.TypePartReflector.Create(TypeParts parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Reflection\TypePartReflector.cs:line 24
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ExtendedXmlSerializer.Core.Sources.CacheBase`2.Get(TKey key) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\Core\Sources\CacheBase.cs:line 34
   at ExtendedXmlSerializer.ContentModel.Reflection.TypeParser.Create(String parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Reflection\TypeParser.cs:line 22
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ExtendedXmlSerializer.Core.Sources.CacheBase`2.Get(TKey key) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\Core\Sources\CacheBase.cs:line 34
   at ExtendedXmlSerializer.ContentModel.Reflection.ReflectionParser.Create(String parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Reflection\ReflectionParser.cs:line 41
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ExtendedXmlSerializer.Core.Sources.CacheBase`2.Get(TKey key) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\Core\Sources\CacheBase.cs:line 34
   at ExtendedXmlSerializer.ExtensionModel.Xml.FormatReaderContext.Get(String parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ExtensionModel\Xml\FormatReaderContext.cs:line 19
   at ExtendedXmlSerializer.ExtensionModel.Xml.XmlReader.Get(String parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ExtensionModel\Xml\XmlReader.cs:line 29
   at ExtendedXmlSerializer.ContentModel.Format.ParsedContent`1.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Format\ParsedContent.cs:line 16
   at ExtendedXmlSerializer.ContentModel.Format.ContextualReader`1.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Format\ContextualReader.cs:line 17
   at ExtendedXmlSerializer.ContentModel.DecoratedReader`1.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\DecoratedReader.cs:line 26
   at ExtendedXmlSerializer.ContentModel.Reflection.TypedParsingReader.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Reflection\TypedParsingReader.cs:line 15
   at ExtendedXmlSerializer.ContentModel.TrackingReader`1.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\TrackingReader.cs:line 16
   at ExtendedXmlSerializer.ContentModel.Members.Extensions.GetIfAssigned[T](IReader`1 this, IFormatReader reader) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Members\Extensions.cs:line 12
   at ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:line 22
   at ExtendedXmlSerializer.ContentModel.Properties.Property`1.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Properties\Property.cs:line 17
   at ExtendedXmlSerializer.ContentModel.Reflection.Classification.FromAttributes(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Reflection\Classification.cs:line 36
   at ExtendedXmlSerializer.ContentModel.Reflection.Classification.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Reflection\Classification.cs:line 32
   at ExtendedXmlSerializer.ContentModel.RuntimeSerializer.Get(IFormatReader reader) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\RuntimeSerializer.cs:line 25
   at ExtendedXmlSerializer.ContentModel.Members.Extensions.GetIfAssigned[T](IReader`1 this, IFormatReader reader) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Members\Extensions.cs:line 12
   at ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:line 22
   at ExtendedXmlSerializer.ContentModel.Members.MemberSerializer.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Members\MemberSerializer.cs:line 22
   at ExtendedXmlSerializer.ContentModel.Members.MemberHandler.Handle(IInnerContent contents, IMemberSerializer member) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Members\MemberHandler.cs:line 13
   at ExtendedXmlSerializer.ContentModel.Content.InnerContentServices.Handle(IInnerContent contents, IMemberSerializer member) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Content\InnerContentServices.cs:line 41
   at ExtendedXmlSerializer.ContentModel.Members.MemberInnerContentHandler.IsSatisfiedBy(IInnerContent parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Members\MemberInnerContentHandler.cs:line 31
   at ExtendedXmlSerializer.ContentModel.Content.InnerContentReader.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Content\InnerContentReader.cs:line 26
   at ExtendedXmlSerializer.ContentModel.Members.Extensions.GetIfAssigned[T](IReader`1 this, IFormatReader reader) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Members\Extensions.cs:line 12
   at ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:line 22
   at ExtendedXmlSerializer.ContentModel.SerializerAdapter`1.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\SerializerAdapter.cs:line 41
   at ExtendedXmlSerializer.ExtensionModel.References.ReferenceAwareSerializers.Serializer.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ExtensionModel\References\ReferenceAwareSerializers.cs:line 54
   at ExtendedXmlSerializer.ContentModel.Members.Extensions.GetIfAssigned[T](IReader`1 this, IFormatReader reader) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Members\Extensions.cs:line 12
   at ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:line 22
   at ExtendedXmlSerializer.ContentModel.Members.Extensions.GetIfAssigned[T](IReader`1 this, IFormatReader reader) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Members\Extensions.cs:line 12
   at ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:line 22
   at ExtendedXmlSerializer.ContentModel.Members.Extensions.GetIfAssigned(IReader this, IFormatReader reader) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Members\Extensions.cs:line 15
   at ExtendedXmlSerializer.ContentModel.Collections.CollectionContentsHandler.Handle(IListInnerContent contents, IReader reader) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Collections\CollectionContentsHandler.cs:line 13
   at ExtendedXmlSerializer.ContentModel.Content.InnerContentServices.Handle(IListInnerContent contents, IReader reader) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Content\InnerContentServices.cs:line 43
   at ExtendedXmlSerializer.ContentModel.Collections.CollectionInnerContentHandler.IsSatisfiedBy(IInnerContent parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Collections\CollectionInnerContentHandler.cs:line 27
   at ExtendedXmlSerializer.ContentModel.Collections.CollectionWithMembersInnerContentHandler.IsSatisfiedBy(IInnerContent parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Collections\CollectionWithMembersInnerContentHandler.cs:line 19
   at ExtendedXmlSerializer.ContentModel.Content.InnerContentReader.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Content\InnerContentReader.cs:line 26
   at ExtendedXmlSerializer.ContentModel.Members.Extensions.GetIfAssigned[T](IReader`1 this, IFormatReader reader) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Members\Extensions.cs:line 12
   at ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:line 22
   at ExtendedXmlSerializer.ContentModel.Members.Extensions.GetIfAssigned[T](IReader`1 this, IFormatReader reader) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Members\Extensions.cs:line 12
   at ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:line 22
   at ExtendedXmlSerializer.ContentModel.Members.MemberSerializer.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Members\MemberSerializer.cs:line 22
   at ExtendedXmlSerializer.ContentModel.Members.MemberHandler.Handle(IInnerContent contents, IMemberSerializer member) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Members\MemberHandler.cs:line 13
   at ExtendedXmlSerializer.ContentModel.Content.InnerContentServices.Handle(IInnerContent contents, IMemberSerializer member) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Content\InnerContentServices.cs:line 41
   at ExtendedXmlSerializer.ContentModel.Members.MemberInnerContentHandler.IsSatisfiedBy(IInnerContent parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Members\MemberInnerContentHandler.cs:line 31
   at ExtendedXmlSerializer.ContentModel.Content.InnerContentReader.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Content\InnerContentReader.cs:line 26
   at ExtendedXmlSerializer.ContentModel.Members.Extensions.GetIfAssigned[T](IReader`1 this, IFormatReader reader) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Members\Extensions.cs:line 12
   at ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:line 22
   at ExtendedXmlSerializer.ExtensionModel.Xml.MigrationsExtension.Contents.Serializer.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ExtensionModel\Xml\MigrationsExtension.cs:line 142
   at ExtendedXmlSerializer.ContentModel.SerializerAdapter`1.Get(IFormatReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ContentModel\SerializerAdapter.cs:line 41
   at ExtendedXmlSerializer.ExtensionModel.Xml.Read.Get(XmlReader parameter) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ExtensionModel\Xml\Read.cs:line 26
   at ExtendedXmlSerializer.ExtensionModel.Xml.Serializer.Deserialize(XmlReader reader) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ExtensionModel\Xml\Serializer.cs:line 21
   at ExtendedXmlSerializer.ExtensionModel.Xml.ExtendedXmlSerializer.Deserialize(XmlReader reader) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ExtensionModel\Xml\ExtendedXmlSerializer.cs:line 18
   at ExtendedXmlSerializer.ExtensionMethodsForSerialization.Deserialize[T](IExtendedXmlSerializer this, XmlReaderSettings settings, Stream stream) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ExtensionMethodsForSerialization.cs:line 145
   at ExtendedXmlSerializer.ExtensionMethodsForSerialization.Deserialize[T](IExtendedXmlSerializer this, XmlReaderSettings settings, String data) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ExtensionMethodsForSerialization.cs:line 121
   at ExtendedXmlSerializer.ExtensionMethodsForSerialization.Deserialize[T](IExtendedXmlSerializer this, String data) in C:\Users\mrapka\source\repos\ExtendedXmlSerializerOrig\src\ExtendedXmlSerializer\ExtensionMethodsForSerialization.cs:line 109
   at ExtendedXmlSerializer.Tests.Performance.MigrationInterfaceNamespaceIssue.Run()

```

**Comment by imperiobadgo** [comment] 2021-03-26 09:50
When I use the `UseOptimizedNamespaces` Extension, the error is gone, but the runtime performance is also worse.

**Comment by Mike-E-angelo** [comment] 2021-03-26 09:54
Thank you for reporting this @imperiobadgo.  I did take a look into it and it appears the `ns1` is not being resolved somehow.  Looks like we both found the workaround in tandem. 😅  I will look further into this and see if I can find the root cause.

FWIW, `UseOptimizedNamespaces` does a reference walk through the entire graph so it knows which namespaces to emit at the root element, essentially serializing twice, hence the performance drag.

**Comment by Mike-E-angelo** [comment] 2021-03-26 15:12
Alright I did take a look into this and unfortunately this is not an easy fix.  Keep in mind the migration story was a v1 feature that was ported to v2, as well as the entire `XElement/XmlReader` APIs are difficult to work with and were a motivating factor in making EXS in the first place.

The issue is with namespace resolution.  This is done by calling the `IXmlNamespaceResolver.LookupNamespace` method which in turn reads from the associated NameTable to get the prefix/namespace from the document.  In the case of the `XElement` that is created via `System.Xml.XmlReader.ReadSubtree()` for the migration, this is retuning `null` no matter what.

I even tried taking the `XElement` and adding all namespace attributes found within the subtree to the root element (something like [this](https://stackoverflow.com/questions/17599654/linq2xml-moving-all-namespace-declarations-to-root-element)) and still no dice.

My best guess is that the generated namespace isn't actually used/accessed anywhere, therefore the table never adds it as an actual namespace.  What's interesting is that the name table has the entry for both the namespace prefix and value.  So it's there, but it isn't being returned as a value as it hasn't been encountered yet in the document graph.

Unfortunately, I do not have more time to look further into this, so I will leave this one up for grabs for the community to look into and hopefully solve.

**Comment by imperiobadgo** [comment] 2021-03-26 15:28
Ok, I can look further and see if I can find any solutions. In any case, thank you very much for trying!

**Comment by Mike-E-angelo** [comment] 2021-03-27 12:20
Alright, I couldn't let this one go. 😅  To start, I got confused between `XmlNameTable` and `XmlNamespaceManager`.  `XmlNameTable` is the cache of string/name values, and not the namespaces (just the values of such).

Anyways, I was able to figure it out.  Finally. :p You can try this out here:
https://github.com/ExtendedXmlSerializer/home/pull/518#issuecomment-808724090

**Comment by imperiobadgo** [comment] 2021-03-27 12:30
You are just great! Now you haven't even given me the chance to find a solution myself 😅

I'll test the build and report my reults.

**Comment by imperiobadgo** [comment] 2021-03-27 13:52
Unfortunately, I have found another mistake. I get an InvalidOperationException when I execute the following function:

```
using ExtendedXmlSerializer.Configuration;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Xml.Linq;

namespace ExtendedXmlSerializer.Tests.Performance
{
  class MigrationDoubleAttributeIssue
  {
    public static void Run()
    {
      var container = new ContainerNameSpace.Container();
      for (int i = 0; i < 1; i++)
      {
        container.Childrens.Add(new ItemNameSpace.Item());
      }

      IConfigurationContainer config = new ConfigurationContainer();
      config.Type<ContainerNameSpace.Container>().AddMigration(new EmptyMigration());
      var serializer = config.Create();

      var output = serializer.Serialize(container);
      // Exception is thrown: InvalidOperationException
      var loaded = serializer.Deserialize<ContainerNameSpace.Container>(output);
    }

    public class EmptyMigration : IEnumerable<Action<XElement>>
    {
      public IEnumerator<Action<XElement>> GetEnumerator()
      {
        yield return x => { }; //Do nothing
      }

      IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

    }

  }

  namespace ContainerNameSpace
  {
    class Container
    {
      public List<ItemNameSpace.Item> Childrens { get; set; } = new List<ItemNameSpace.Item>();
    }
  }

  namespace ItemNameSpace
  {
    class Item { }
  }

}
```

**Comment by Mike-E-angelo** [comment] 2021-03-27 14:15
Doh, forgot to check if the added attribute was already added.  Try this one:

https://github.com/ExtendedXmlSerializer/home/pull/518#issuecomment-808739734

**Comment by imperiobadgo** [comment] 2021-03-27 15:32
Seems to work perfectly now! Thank you very much!

**Comment by Mike-E-angelo** [comment] 2021-03-30 03:34
This has been posted to NuGet:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Please let me know if you run into any additional problems and I will take a look into it for you.  Closing for now.

**Closed by Mike-E-angelo** 2021-03-30 03:34 UTC
Labels: bug, system.xml.serialization
