### ISSUE TITLE
Dictionary inside list serialization error

### ISSUE THREAD

**Issue by maxkoshevoi** [ExtendedXmlSerializer/home#423] opened 2020-08-11 15:50 UTC
I have following code structure:

![image](https://user-images.githubusercontent.com/6609929/89908102-2b1d4e00-dbf6-11ea-9e44-7d65373354da.png)

And when serializing it this error occurs: `System.ArgumentNullException: 'Value cannot be null. Parameter name: key'`
Stack:
```  at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at ExtendedXmlSerializer.ExtensionModel.Xml.XmlWriter.CreatePrefix(String identifier)
   at ExtendedXmlSerializer.ExtensionModel.Xml.XmlWriter.Get(TypeParts parameter)
   at ExtendedXmlSerializer.ExtensionModel.Xml.XmlWriter.GetType(TypeInfo parameter)
   at ExtendedXmlSerializer.ExtensionModel.Xml.XmlWriter.Get(MemberInfo parameter)
   at ExtendedXmlSerializer.ExtensionModel.Xml.OptimizedNamespaceXmlWriter.Get(MemberInfo parameter)
   at ExtendedXmlSerializer.ContentModel.Format.FormattedContent`1.Get(IFormatWriter writer, T instance)
   at ExtendedXmlSerializer.ContentModel.Format.ContextualWriter`1.Write(IFormatWriter writer, T instance)
   at ExtendedXmlSerializer.ContentModel.DecoratedWriter`1.Write(IFormatWriter writer, T instance)
   at ExtendedXmlSerializer.ContentModel.Serializer`1.Write(IFormatWriter writer, T instance)
   at ExtendedXmlSerializer.ContentModel.Properties.Property`1.Write(IFormatWriter writer, T instance)
   at ExtendedXmlSerializer.ContentModel.Collections.ArrayIdentity.Write(IFormatWriter writer, Array instance)
   at ExtendedXmlSerializer.ContentModel.GenericWriterAdapter`1.Write(IFormatWriter writer, Object instance)
   at ExtendedXmlSerializer.ContentModel.Content.Enclosure`1.Write(IFormatWriter writer, T instance)
   at ExtendedXmlSerializer.ContentModel.SerializerAdapter`1.Write(IFormatWriter writer, T instance)
   at ExtendedXmlSerializer.ExtensionModel.RootInstanceExtension.Serializer.Write(IFormatWriter writer, Object instance)
   at ExtendedXmlSerializer.ExtensionModel.Xml.Write.Execute(Writing parameter)
   at ExtendedXmlSerializer.ExtensionModel.Xml.Serializer.Serialize(XmlWriter writer, Object instance)
   at ExtendedXmlSerializer.ExtensionModel.Xml.ExtendedXmlSerializer.Serialize(XmlWriter writer, Object instance)
   at ExtendedXmlSerializer.ExtensionModel.Xml.InstanceFormatter.Get(Object parameter)
   at ExtendedXmlSerializer.ExtensionMethodsForSerialization.Serialize(IExtendedXmlSerializer this, XmlWriterSettings settings, Object instance)```

If this object is serialized by itself (and not inside the list) everything works fine.

**Comment by Mike-E-angelo** [comment] 2020-08-11 16:09
Thanks for reporting this, @maxkoshevoi.  Unfortunately I was not able to reproduce this by eyeballing your schema.  I may have overlooked something though.  Here is the passing test in our suite:

https://github.com/ExtendedXmlSerializer/home/blob/147e8a80acc67b0fd50ce383c3ab5d850402abe0/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue423Tests.cs

Could I bother you to get a minimal repro with code you are using that generates this error?  It could be party due to how you are configuring the container as well.

**Comment by Mike-E-angelo** [comment] 2020-08-11 16:16
FWIW I did have an inaccuracy, in that I was not using multiple dictionaries within each instance.  I have addressed this and updated the test here:

https://github.com/ExtendedXmlSerializer/home/blob/744f3e628116cfad4460401fb41710b0d6c2b72e/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue423Tests.cs

It still passes, and I am actually entirely surprised that it does. 😅

**Comment by maxkoshevoi** [comment] 2020-08-11 17:03
Thanks for quick response! Here is console app that reproduces the issue: https://github.com/maxkoshevoi/ExtendedXmlSerializer-423

![image](https://user-images.githubusercontent.com/6609929/89926386-7bec7100-dc0d-11ea-98b7-e8bf32a37640.png)

**Comment by Mike-E-angelo** [comment] 2020-08-11 18:24
OK great, thank you for that.  Looks like the issue is with `EnableImplicitTypingFromNamespace`.  If I remove that it appears to work OK.  I will dig around and see if this can be patched up.

**Comment by Mike-E-angelo** [comment] 2020-08-11 18:28
Ah, to be more specific it has to do with combining several extensions.  I am able to reproduce this with the following configuration:

```
var serializer = new ConfigurationContainer().UseOptimizedNamespaces().EnableImplicitTyping(typeof(NewOptionSetFieldInfo)).Create();
```

**Comment by maxkoshevoi** [comment] 2020-08-11 18:51
Yeah, I have `EnableImplicitTypingFromNamespace` cause as you can see I have several models that extend each other (more than in the provided sample) and I need to serialize and deserialize list of all of them. And `UseOptimizedNamespaces` is kink of a best practice, right?

**Comment by Mike-E-angelo** [comment] 2020-08-11 19:15
Yes you are correct.  There shouldn't be a problem with combining these extensions and this all _should_ work.

Looking into it further, it's a very specific set of conditions:

- `UseOptimizedNamespaces`
- `EnableImplicitTyping*`
- Use of read-only list/dictionary property.
- Root instance of `T[]`.

I have been able to reproduce it with this as a minimum:

```
[Fact]
public void VerifyReported()
{
	var subject = new Subject();
	var element = new[] { subject };

	var serializer = new ConfigurationContainer().UseOptimizedNamespaces()
	                                             .EnableImplicitTyping(typeof(Subject))
	                                             .Create();
	serializer.Serialize(element);

}


sealed class Subject
{
	public List<string> Values { get; } = new List<string>();
}
```

Note that if I do the following it works:

```
var element = new[] { subject }.ToList();
```

I would be interested in seeing that unblocks you for the time-being as I track this down.

**Comment by maxkoshevoi** [comment] 2020-08-11 19:22
I used array instead of list, case List serializes with capacity info. So there is excess data in serialized XML and I think users can break serialization by changing it (or by not changing it and adding elements to the list).
This issue is not super urgent, it can wait a couple of days. I will revert to using list if there wouldn't be a fix by then. 
Thank you for such quick troubleshooting and workaround!

**Comment by Mike-E-angelo** [comment] 2020-08-11 19:28
Yep, I hear you on the `Capacity`.  You can configure to ignore it but it's a bit of a hassle. 

FWIW I found another workaround for you that allows you to use `Array`.  You have to add it as an implicit type.  You can do the following:

```
var serializer = new ConfigurationContainer().UseOptimizedNamespaces()
											 .EnableImplicitTyping(new AllTypesInSameNamespace<NewOptionSetFieldInfo>().Append(typeof(Array)))
											 .Create();
```

That _seems_ to work, but would be interested in knowing on your side if there are any further issues you find with it.

**Comment by maxkoshevoi** [comment] 2020-08-11 20:16
Looks solid. I think I'll use that one for the meanwhile.
Thank you, I'll reach out if there will be any issues.

**Comment by Mike-E-angelo** [comment] 2020-08-11 20:21
Cool!  Yeah, this looks like a tricky one so it might be a bit before I get a fix in.  I should be able to dedicate some time tomorrow and will update here with any news. 👍

**Comment by Mike-E-angelo** [comment] 2020-08-11 20:47
Alright, good news @maxkoshevoi I managed to figure out a fix:
https://github.com/ExtendedXmlSerializer/home/pull/424#issuecomment-672267042

That's the good news.  The bad news is that the fix is in the core `XmlWriter` component which is used by everything.  All our tests pass but even at 1200+ passing tests, it makes me nervous to publish and possibly break someone else out there.  Oh well, such is the life of software development/deployment. 😁

Anyways, let me know if that build treats you better.  I release every Tuesday, but since this one might be impacting I will let it sit until next Tuesday and see if I can think of a better solution.  Please feel free to use the preview build until then (and let me know of any further issues you encounter).

**Comment by Mike-E-angelo** [comment] 2020-08-18 07:36
This has been deployed to NuGet:

https://www.nuget.org/packages/ExtendedXmlSerializer/

Please do let me know of any problems you find and I will investigate.  Thank you for improving the quality of ExtendedXmlSerializer!  Closing this issue for now.

**Closed by Mike-E-angelo** 2020-08-18 07:36 UTC
Labels: bug
