### ISSUE TITLE
Deserialisation terminates silently at element for property marked with XmlIgnoreAttribute

### ISSUE THREAD

**Issue by StuYarrow** [ExtendedXmlSerializer/home#271] opened 2019-11-06 21:11 UTC
This is the last of my questions about deserialising legacy documents, I promise! ;-)

I am finding that `ExtendedXmlSerializer.Deserialize()` stops processing the document if it encounters an element that corresponds to a property that is marked with `XmlIgnoreAttribute`.  Small example below.  You can see that in each case, the document is deserialised correctly, up until the first occurrence of `Entity.Show` (not including the override, `Entity2.Show`).

I think I can work around it, but maybe it is a bug?  If `XmlIgnoreAttribute` was added to an existing member, I think it would break deserialisation of existing documents created by ExtendedXmlSerializer.

```
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.Xml.Serialization;

    using ExtendedXmlSerializer.Configuration;
    using ExtendedXmlSerializer.ExtensionModel.Xml;

    public static class ExtendedXmlSerializerTests
    {
        public static void TerminateOnXmlIgnore()
        {
            var serializer = new ConfigurationContainer()
                .EnableImplicitTyping(typeof(Entity), typeof(Entity2))
                .Create();

            // language=XML
            const string content1 =
                @"<?xml version=""1.0"" encoding=""utf-8""?>
                <Entity>
                    <Name>Foo</Name>
	                <Show>false</Show>
                    <Children>
                        <Entity>
                            <Name>Bar</Name>
                            <Show>false</Show>
                        </Entity>
                        <Entity>
                            <Name>Jim</Name>
                            <Show>true</Show>
                        </Entity>
                    </Children>
                </Entity>";

            const string content2 =
                @"<?xml version=""1.0"" encoding=""utf-8""?>
                <Entity>
                    <Name>Foo</Name>
                    <Children>
                        <Entity>
                            <Name>Bar</Name>
                            <Show>false</Show>
                        </Entity>
                        <Entity>
                            <Name>Jim</Name>
                            <Show>true</Show>
                        </Entity>
                    </Children>
	                <Show>false</Show>
                </Entity>";

            const string content3 =
                @"<?xml version=""1.0"" encoding=""utf-8""?>
                <Entity2>
                    <Name>Foo</Name>
                    <Children>
                        <Entity2>
                            <Name>Bar</Name>
                            <Show>false</Show>
                        </Entity2>
                        <Entity2>
                            <Name>Jim</Name>
                            <Show>true</Show>
                        </Entity2>
                    </Children>
	                <Show>false</Show>
                </Entity2>";

            // result1.Children.Count = 0
            var result1 = serializer.Deserialize<Entity>(content1);

            // result2.Children.Count = 1
            var result2 = serializer.Deserialize<Entity>(content2);

            // result3.Children.Count = 2
            var result3 = serializer.Deserialize<Entity2>(content3);
        }
    }

    public class Entity
    {
        public string Name { get; set; }

        [XmlIgnore]
        public virtual bool Show
        {
            get => true;
            set { }
        }

        public List<Entity> Children { get; } = new List<Entity>();
    }

    public class Entity2 : Entity
    {
        [DataMember]
        public override bool Show { get; set; }
    }
```

**Comment by Mike-EEE** [comment] 2019-11-06 22:12
Hah!  No worries, @StuYarrow ... like I said we try to get these squared away where we can.  This one sounds like a bug, however, and I will look into it and let you know. 👍

**Comment by Mike-EEE** [comment] 2019-11-07 08:31
OK I found the problem here @StuYarrow ... the issue is the EXS `XmlReader` which is easily the biggest sore that I created in this codebase, namely how it interacts with the native `System.Xml.XmlReader`.  I have done a lot to work around it, but there are still a lot of rough spots.

In this case, the reader is encountering an invalid element and simply stops.  Originally when we designed this we wanted to keep `try/catch`-s out of the code as much as possible as they impede performance (I have introduced a lot since then that has easily impacted performance equal-to, if not greater so BUT WE WON'T GO THERE. 😆), so that was the rationale behind this.

We do have the `ConfigurationContainer.EnableUnknownContentHandling` extension method, but more work is required to utilize it for either continuing or throwing exceptions, so I recommend including two new extension methods:

`ConfigurationContainer.ThrowOnUnknownContent` - This will throw an exception when unknown content within an XML Document is encountered.

`ConfigurationContainer.ContinueOnUnknownContent` - This will configure both the EXS and native `XmlReader` to essentially perform a read and allow it to continue reading and parsing the document.

I will work on these and have them available on our preview feed shortly.

**Comment by Mike-EEE** [comment] 2019-11-07 09:20
Alright @StuYarrow I have posted some code demonstrating the new usage here:
https://github.com/WojciechNagorski/ExtendedXmlSerializer/blob/afbafd6acc6a09ed620ce0acfdf67b89dc4d6132/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue256Tests.cs#L18-L57

Unfortunately, it seems our preview feed is no longer being propagated.  I will discuss this with @WojciechNagorski and let you know of any updates.

**Comment by StuYarrow** [comment] 2019-11-07 09:24
Many thanks!  I have the EXS project in my solution for debugging at the moment, so its easy to pull in those changes.

**Comment by Mike-EEE** [comment] 2019-11-07 10:28
Cool!  That works even better. 😁

**Comment by Mike-EEE** [comment] 2019-11-08 16:08
FWIW our preview feed is back:

https://www.myget.org/F/wojtpl2/api/v3/index.json

**Comment by Mike-EEE** [comment] 2019-12-03 08:17
This has been released in the latest version which can be found here:

https://www.nuget.org/packages/ExtendedXmlSerializer/

Further details on the release can be found here:

https://github.com/ExtendedXmlSerializer/home/releases/tag/3.0.0

If you run into any problems or have further questions, please feel free to open a new issue and we'll take a look.  Thank you for improving ExtendedXmlSerializer!

**Closed by Mike-EEE** 2019-12-03 08:17 UTC
Labels: documentation, enhancement
