### ISSUE TITLE
Any way to serialize private members?

### ISSUE THREAD

**Issue by leryss** [ExtendedXmlSerializer/home#265] opened 2019-09-26 07:19 UTC
Title

**Comment by Mike-EEE** [comment] 2019-09-26 14:39
Hey, @leryss thanks for writing in.  Amazingly, we do not ATM, but I believe we can make it happen.  Are you wanting to serialize _all_ private members or those that are marked with `XmlElementAttribute` (or `XmlAttributeAttribute`)?

**Comment by leryss** [comment] 2019-09-26 14:47
I would like to serialize all fields regardless of access level or annotations.

**Comment by Mike-EEE** [comment] 2019-10-12 11:14
Alright... sorry for the delay here I have been out of town and have been settling back in.  I've got this on the radar for either today or tomorrow. 👍

**Comment by Mike-EEE** [comment] 2019-10-16 05:52
Boh... I was incorrect, @leryss.  It does look like we have support already via the classic attribute model.  Here is example code:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/d609197f9bb3d61de838cb43d826c00798bd2256/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue265Tests.cs#L11-L32

So, utilizing `System.Xml.Serialization.XmlElementAttribute` (and/or System.Xml.Serialization.XmlAttributeAttribute`) will allow you to serialize private fields.  Is this sufficient for your scenario?

**Comment by marcodiniz** [comment] 2019-11-04 20:57
I have almost the same needs. 

But my private field is on the base class. The XmlElementAttribute only works if the field is on the concret class being des/serialized

**Comment by Mike-EEE** [comment] 2019-11-04 22:02
Ah good point, @marcodiniz.  I have made an adjustment to pull from runtime fields instead, which include inherited fields.  

However, after implementing this, of course, I realized it wasn't exactly the same as what you're after. 😞  I will have to add this tomorrow when I have more time.

If you are able to make your fields `protected` you can use the adjustment I just committed, though.  I have added a passing test demonstrating it here:

https://github.com/WojciechNagorski/ExtendedXmlSerializer/blob/2c929f47c4574ef0dd7e90a9326ac888190b6d21/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue265Tests.cs#L23-L51

You can get the latest version from our preview feed here:
https://www.myget.org/F/wojtpl2/api/v3/index.json

I will look into this more when I have the time. 👍

**Comment by Mike-EEE** [comment] 2019-11-05 08:23
Actually now thinking about this, this might be by design.  Consider the following graph:

```
		class Base
		{
			[XmlElement] string _message;

			public Base() : this("Default Value") {}

			public Base(string test) => _message = test;

			public string Message() => _message;
		}

		class Inherited : Base
		{
			[XmlElement] string _message;

			public Inherited() {}

			public Inherited(string test) : base(test) {}

			...
		}
```

When `_message` is serialized, which one will it be?  I suppose that we could do both, but that would involve applying namespaces to fields, which would involve a lot of effort at this point, unfortunately.  Especially for such a unique scenario.

I'm open to further thoughts around this.

**Comment by Mike-EEE** [comment] 2019-12-03 08:15
This has been released in the latest version which can be found here:

https://www.nuget.org/packages/ExtendedXmlSerializer/

Further details on the release can be found here:

https://github.com/ExtendedXmlSerializer/home/releases/tag/3.0.0

If you run into any problems or have further questions, please feel free to open a new issue and we'll take a look.  Thank you for improving ExtendedXmlSerializer!

**Closed by Mike-EEE** 2019-12-03 08:15 UTC
Labels: documentation, enhancement
