### ISSUE TITLE
EnableReferences use case

### ISSUE THREAD

**Issue by SuperJMN** [ExtendedXmlSerializer/home#418] opened 2020-07-21 10:19 UTC
I'm trying to understand the usage of the `EnableReferences`. I've created this sample to wrap my head around the concept and I'm getting an unexpected result.

Basically, I have a BookStore with Books (with all the books) and Genres that have references to the books.

## Expected
The resulting XML of the Genres section should hold references to each book.

## Actual result
The resulting XML holds references to a list of Books instead.

## How to reproduce
This is the offending code:

```
void Main()
{

	string OutputXml = System.IO.Path.GetTempFileName() + ".xml";

	var b1 = new Book();
	var b2 = new Book();
	
	var allBooks = new[] { b1, b2, };

	var fs = new BookStore()
	{
		AllBooks = allBooks,
		Genres = new[]
		{
			new Genre()
			{
				Books = allBooks,
			},
			new Genre()
			{
				Books = allBooks,
			},
		}
	};

	var serializer = new ConfigurationContainer()
		.Type<Book>(b => b.EnableReferences())
		.Create();

	var serialized = serializer.Serialize(new XmlWriterSettings() { Indent = true }, fs);

	System.IO.File.WriteAllText(OutputXml, serialized);

	var psi = new ProcessStartInfo(OutputXml)
	{
		UseShellExecute = true,
	};
	Process.Start(psi);
}

class BookStore
{
	public IEnumerable<Book> AllBooks { get; set; }
	public IEnumerable<Genre> Genres { get; set; }
}

class Book
{	
}

class Genre
{
	public IEnumerable<Book> Books { get; set; }
}
```

As you see, both genres have a reference to `allBooks`. The serializer identifies that I want to reflect this in the XML, but I would like to have the reference to the actual books inside `allBook`.

### NOTE
In order to get the desired results I would have to use the following code:

```
void Main()
{

	string OutputXml = System.IO.Path.GetTempFileName() + ".xml";

	var b1 = new Book();
	var b2 = new Book();
	
	var allBooks = new[] { b1, b2, };

	var fs = new BookStore()
	{
		AllBooks = allBooks,
		Genres = new[]
		{
			new Genre()
			{
				Books = new[] { b1, b2 },
			},
			new Genre()
			{
				Books = new[] { b1, b2 },
			},
		}
	};

	var serializer = new ConfigurationContainer()
		.Type<Book>(b => b.EnableReferences())
		.Create();

	var serialized = serializer.Serialize(new XmlWriterSettings() { Indent = true }, fs);

	System.IO.File.WriteAllText(OutputXml, serialized);

	var psi = new ProcessStartInfo(OutputXml)
	{
		UseShellExecute = true,
	};
	Process.Start(psi);
}
```

Once the Books are assigned to different references (2 different arrays), the correct XML is produced.

I've configured the serialized calling the `config.Type<Book>(b => b.EnableReferences())` because I've expected this would cause the Book to be reference from another places in the XML, but I think I've misunderstood its usage.

Is this a bug or I'm failing to tell the serializer what I want :)

**Comment by Mike-E-wins** [comment] 2020-07-21 12:34
Thank you for reporting this, @SuperJMN!  My first thought was to attempt `EnableReferences` on the entire container, but there appears to be an issue that is like #360 when using arrays.  This *should* work, however.  Let me see if this is salvageable. 🤞

**Comment by Mike-E-wins** [comment] 2020-07-21 12:48
I should also note that the reason why you are having issues with references is that you are configuring `Type<Book>()` and the reference that you are wanting to serialize is `Type<Book[]>()` (or `Type<IEnumerable<Book>>()`.  However, all of that fails due to the above issue.

Also, `Type<Book>(b => b.EnableReferences())` works just like `Type<Book>().EnableReferences()` and is just another way of allowing an author to configure the type, so the problem is not that. :)

Looking into this now.

**Comment by Mike-E-wins** [comment] 2020-07-21 16:22
Alright @SuperJMN check out the following build and let me know how it treats you:

https://github.com/ExtendedXmlSerializer/home/pull/420#issuecomment-661956577

**Comment by Mike-E-wins** [comment] 2020-07-21 16:23
"Super" happy to report that this fixes #360, too! 🎉

😁

**Comment by SuperJMN** [comment] 2020-07-21 16:50
Wow.
FASTER THAN FAST!

I've reviewed the changes you did to fix this and the test even uses the very same example I used to report the issue.

Thank you so much for the time and effort you've put into this!

**Comment by Mike-E-wins** [comment] 2020-07-21 17:59
I have deployed this to NuGet:

https://www.nuget.org/packages/ExtendedXmlSerializer/

Please do give it a whirl and let me know if you find any issues. 👍

Closing this for now.

**Closed by Mike-E-wins** 2020-07-21 17:59 UTC
Labels: bug, question

**Comment by SuperJMN** [comment] 2020-07-22 12:12
Hello! I've tried the fixed code with another (more complex) use case and it's failing on me.

If you try this code:

```
void Main()
{

	string OutputXml = System.IO.Path.GetTempFileName() + ".xml";

	var b1 = new Book();
	var b2 = new Book();
	var b3 = new Book();
	var b4 = new Book();
	var b5 = new Book();
	var b6 = new Book();

	var historyBooks = new[] { b1, b2, };
	var artBooks = new[] { b3, b4, };
	var scienceBooks = new[] { b5 };
	var comics = new[] { b6 };
	
	var all = historyBooks.Concat(artBooks).Concat(scienceBooks).Concat(comics).ToList();

	var fs = new BookStore()
	{
		AllBooks = all,
		Genres = new[]
		{
			new Genre()
			{
				Books = historyBooks,
			},
			new Genre()
			{
				Books = historyBooks,
			},
			new Genre()
			{
				Books = artBooks,
			},
			new Genre()
			{
				Books = scienceBooks,
			},
			new Genre()
			{
				Books = comics,
			},
		}
	};

	var serializer = new ConfigurationContainer()
		.Type<Book>(b => b.EnableReferences())
		.Create();

	var serialized = serializer.Serialize(new XmlWriterSettings() { Indent = true }, fs);

	System.IO.File.WriteAllText(OutputXml, serialized);

	var psi = new ProcessStartInfo(OutputXml)
	{
		UseShellExecute = true,
	};
	Process.Start(psi);
}

class BookStore
{
	public IEnumerable<Book> AllBooks { get; set; }
	public IEnumerable<Genre> Genres { get; set; }
}

class Book
{	
}

class Genre
{
	public IEnumerable<Book> Books { get; set; }
}
```

You will get this XML:

```
<?xml version="1.0" encoding="utf-8"?>
<UserQuery-BookStore xmlns="clr-namespace:;assembly=LINQPadQuery">
  <AllBooks xmlns:sys="https://extendedxmlserializer.github.io/system" xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="sys:List[UserQuery-Book]">
    <Capacity>6</Capacity>
    <UserQuery-Book exs:identity="2" />
    <UserQuery-Book exs:identity="3" />
    <UserQuery-Book exs:identity="4" />
    <UserQuery-Book exs:identity="5" />
    <UserQuery-Book exs:identity="6" />
    <UserQuery-Book exs:identity="7" />
  </AllBooks>
  <Genres xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="UserQuery-Genre^1">
    <UserQuery-Genre>
      <Books exs:type="UserQuery-Book^1" exs:identity="1">
        <UserQuery-Book exs:reference="2" />
        <UserQuery-Book exs:reference="3" />
      </Books>
    </UserQuery-Genre>
    <UserQuery-Genre>
      <Books exs:type="UserQuery-Book^1" exs:reference="1" />
    </UserQuery-Genre>
    <UserQuery-Genre>
      <Books exs:type="UserQuery-Book^1">
        <UserQuery-Book exs:reference="4" />
        <UserQuery-Book exs:reference="5" />
      </Books>
    </UserQuery-Genre>
    <UserQuery-Genre>
      <Books exs:type="UserQuery-Book^1">
        <UserQuery-Book exs:reference="6" />
      </Books>
    </UserQuery-Genre>
    <UserQuery-Genre>
      <Books exs:type="UserQuery-Book^1">
        <UserQuery-Book exs:reference="7" />
      </Books>
    </UserQuery-Genre>
  </Genres>
</UserQuery-BookStore>
```

I expected to get a `<UserQuery-Book exs:identity="1" />` inside the AllBooks section. It's skipping item 1 and the first Genre is using "identity" where it should use "reference" like the rest of the genres.

Is is a bug or I'm misunderstanding something? :)

**Comment by Mike-E-angelo** [comment] 2020-07-22 13:45
Ah, ok!  When you say it's failing for you, are you experiencing an error?

FWIW I used the code you provided above (thank you!) and made a passing test here:
https://github.com/ExtendedXmlSerializer/home/blob/e8abfa35a96d5db90f6f3471f3545a1aa6a3be6a/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue418Tests_Extended.cs#L12-L68

If you are concerned with the `identity="1"` seeming out of place, that is by design when you let EXS label the identities for you.  An internal counter is used and is incremented whenever a reference is encountered.

I've also added a test that demonstrates the use of applying explicit identity, where if you set the identity field, it makes a little cleaner XML for you:

https://github.com/ExtendedXmlSerializer/home/blob/e8abfa35a96d5db90f6f3471f3545a1aa6a3be6a/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue418Tests_Extended.cs#L70-L83

Here's the XML for your reference:

```
<?xml version="1.0" encoding="utf-8"?>
<Array xmlns:ns1="clr-namespace:ExtendedXmlSerializer.Tests.ReportedIssues;assembly=ExtendedXmlSerializer.Tests.ReportedIssues" xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:item="ns1:Issue418Tests_Extended-Book" xmlns="https://extendedxmlserializer.github.io/system">
	<ns1:Issue418Tests_Extended-Book Id="123" />
	<ns1:Issue418Tests_Extended-Book exs:entity="123" />
</Array>
```

Please do let me know if you are encountering any errors and I will take a look into them for you. 👍

**Comment by Mike-E-angelo** [comment] 2020-07-22 13:50
I guess a possible issue here is that references are being applied to `Book[]` when you have only specified them to `Book`.  That is what is grabbing the first reference increment count and is offsetting the XML in subsequent `Book` encounters.

**Comment by Mike-E-angelo** [comment] 2020-07-22 14:04
DOH @SuperJMN I apologize for the confusion here.  You are giving me quite the memory workout! 😅  It turns out there are two ways of enabling references:

`EnableReferences()` : Enables references to the entire container.
`Type<T>().EnableReferences(x => x.Id)` : Enables references specifically for the type, with the provided member being the identity member.

Unfortunately, despite my best wishes, there is no `Type<T>().EnableReferences()`.  What you are actually doing is calling it on the Type's parent `ConfigurationContainer` thereby enabling it for the entire container.  This explains why both `Book` and `Book[]` are being counted.

The fluent api suffers from some design issues like the above.  You think you're applying it to the type, but you're really accessing the parent container.  It was my first attempt at a fluent API, what can I say. 😁

**Comment by SuperJMN** [comment] 2020-07-22 22:03
Yay! I've just tried adding an Id to the Book class and it works as expected!

This is the code with the workaround

```
void Main()
{

	string OutputXml = System.IO.Path.GetTempFileName() + ".xml";

	var b1 = new Book(1);
	var b2 = new Book(2);
	var b3 = new Book(3);
	var b4 = new Book(4);
	var b5 = new Book(5);
	var b6 = new Book(6);

	var historyBooks = new[] { b1, b2, };
	var artBooks = new[] { b3, b4, };
	var scienceBooks = new[] { b5 };
	var comics = new[] { b6 };
	
	var all = historyBooks.Concat(artBooks).Concat(scienceBooks).Concat(comics).ToList();

	var fs = new BookStore()
	{
		AllBooks = all,
		Genres = new[]
		{
			new Genre()
			{
				Books = historyBooks,
			},
			new Genre()
			{
				Books = historyBooks,
			},
			new Genre()
			{
				Books = artBooks,
			},
			new Genre()
			{
				Books = scienceBooks,
			},
			new Genre()
			{
				Books = comics,
			},
		}
	};

	var serializer = new ConfigurationContainer()
		.Type<Book>(b => b.EnableReferences(x => x.Id))
		.Create();

	var serialized = serializer.Serialize(new XmlWriterSettings() { Indent = true }, fs);

	System.IO.File.WriteAllText(OutputXml, serialized);

	var psi = new ProcessStartInfo(OutputXml)
	{
		UseShellExecute = true,
	};
	Process.Start(psi);
}

class BookStore
{
	public IEnumerable<Book> AllBooks { get; set; }
	public IEnumerable<Genre> Genres { get; set; }
}

class Book
{	
	public Book()
	{		
	}
	
	public Book(int id)
	{
		Id = id;
	}
	public int Id { get; set; }
}

class Genre
{
	public IEnumerable<Book> Books { get; set; }
}
```

The need for an `id` is a minor annoyance. I'd like to be fully automagic, but I think I'm asking for too much this time :)

Big, big thanks for your valuable help, Mike!

**Comment by Mike-E-angelo** [comment] 2020-07-23 05:33
Cool!  Yeah I am surprised that it is implemented container-wide rather than type-specific.  If some brave soul out there wants to submit a PR to enable such functionality I will not complain. :)

In any case, glad you got sorted out.  Please let me know if you have any further questions/issues, and I will do my best to assist you. 👍
