### ISSUE TITLE
Serialization of references

### ISSUE THREAD

**Issue by jhranac** [ExtendedXmlSerializer/home#433] opened 2020-08-27 11:05 UTC
Hello, 

Got a question/issue with reference serialization:

```
var serializer = ... ;
var value = new SomeValue();
var subject = new ClassWithReferences 
{ 
   X = value,
   Y = value
};

serializer.Serialize(subject); // => throws an exception about Circular reference 
```
So my questions / issues are:

1. Why does it think there is a circular reference when there isn't one?
2. Can the serializer write XML in this case for both X and Y ? - I'd expect to have two objects instead of one on deserialization, that's ok.

EDIT:
I do have a custom serializer created for `SomeValue`. So it looks like https://github.com/ExtendedXmlSerializer/home/issues/361 is back.

EDIT2:
I was able to achieve desired behavior by adding types with custom serializer to the `IgnoredReferenceTypes` collection manually.

**Comment by Mike-E-angelo** [comment] 2020-08-27 12:48
Hey, thanks for writing in with the question @jhranac.  You bring up a good point.  The issue is not that it's circular, but that there are multiple instances of the same reference in the graph.  The messaging is misleading in your exact scenario but still closely related to a circular reference condition, as we store encountered references and ensure they are only written once per graph.

If you want to write these anyways, it might be possible to write an extension that swallows that exception and continues the serialization.  Let me know if that is something you are interested in, and/or if you got things situated on your end with your configuration.

**Comment by Mike-E-angelo** [comment] 2020-09-01 09:08
Sounds like we got this question answered for you.  Please do let me know if that is the case and we can take it from there.  Closing this issue for now.

**Closed by Mike-E-angelo** 2020-09-01 09:08 UTC
Labels: question
