### ISSUE TITLE
modified array cannot be deserialized

### ISSUE THREAD

**Issue by aspektxxx** [ExtendedXmlSerializer/home#378] opened 2020-03-16 15:24 UTC
Given test 
```
var serializer = new ConfigurationContainer().Create().ForTesting();
var instance = new Data2();
instance.MyCollection[0] = "data3";
instance.MyCollection[1] = "data4";
serializer.Cycle(instance).Should().BeEquivalentTo(instance);
```
where
```
class Data2
{
	public string[] MyCollection { get; }
	public Data2()
	{
		MyCollection = new string[2] { "data1", "data2" };
	}
}
```
I get 

> System.NotSupportedException : Collection was of a fixed size.
I would expect this can be correctly deserialized

**Comment by Mike-EEE** [comment] 2020-03-17 07:24
This looks weird and definitely a bug, @aspektxxx thank you for reporting it.  Looking into this now.

**Comment by Mike-EEE** [comment] 2020-03-17 08:36
Ah!  Details, @aspektxxx. 😁  This is operating as expected on a read-only collection property (I was thinking it was writable).

However, it's expecting something like:

```
public Collection<string> MyCollection { get; } = new Collection<string>();
```

So this is unsupported although it would be nicer to get a better experience (exception message) to say so.  Would that suffice for your purposes here?

**Comment by Mike-EEE** [comment] 2020-03-17 08:38
I guess the other thing we could do is add another `MemberAccessor`... something like `ReadOnlyArrayMemberAccessor`.  It would be cool to get that in an extension.  I am not sure if member accessors are really that, erm, accessible (irony 😏) to being extended, however.

**Comment by aspektxxx** [comment] 2020-03-17 09:27
@Mike-EEE well, I don't think it works as expected. Its not read only array (collection) so it can be modified. Its also being emitted into xml. I don't see why it should not be possible to deserialize. The fact that the property itself is read only is IMHO irrelevant. 
Anyway, this is not a real issue for me. I came across it when testing how it behaves with collections. I believe current implementation is not consistent.

**Comment by Mike-EEE** [comment] 2020-03-17 09:30
Yeah I agree @aspektxxx I have been looking further into it.  The problem is that we enumerate through values currently and do not have a notion of an indexer.  It would involve some work.  Luckily the member accessor components are all internal so it won't (or shouldn't) introduce breaking changes.

**Comment by Mike-E-wins** [comment] 2020-06-09 12:44
Looking over issues here and this has been open for nearly 3 months.  As per #383 my time for supporting involved issues are limited.  If someone wants to submit a PR I am more than happy to re-open this issue.  We can also revisit this if someone else opens up a similar issue.  As always, please feel free to post any additional thoughts/comments and we can certainly take it from there.  Closing for now.

**Closed by Mike-E-wins** 2020-06-09 12:44 UTC
Labels: bug, help wanted
