### ISSUE TITLE
XmlText not assigning parsed value to the property and its throwing exception

### ISSUE THREAD

**Issue by Lakistein** [ExtendedXmlSerializer/home#391] opened 2020-05-07 14:46 UTC
Hi,

I have an issue with XmlText, I tried few things but I cannot make it work. Maybe I'm missing something.

I have this class:

```
[XmlRoot(ElementName = "classA")]
public class ClassA
{
      [XmlAttribute(AttributeName = "attr")]
      public string Attr { get; }
      [XmlText]
      public string Text { get; }

      private ClassA(string attr, string text)
      {
          Attr = attr;
          Text = text;
      }

      public static ClassA Create(string attr, string text)
      {
          return new ClassA(attr, text);
      }
}
```

and this XML

```
<?xml version=\"1.0\" encoding=\"utf-8\"?>
<classA attr=\"someAttrValue\">SomeInnerText</classA>
```

This is the code:

```
var xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><classA attr=\"someAttrValue\">SomeInnerText</classA>";
using (var memoryStream = new MemoryStream(Encoding.UTF8.GetBytes(xml)))
{
      ser = new ConfigurationContainer()
                        .EnableAllConstructors()
                        .EnableImplicitTypingFromAll<ClassA>()
                        .EnableParameterizedContent()
                        .EnableMemberExceptionHandling()
                        .EnableXmlText()
                        .Create();
      var result = (ClassA)ser.Deserialize<ClassA>(memoryStream);
}
```

Basically the deserialization works fine, apart from Text property, which is null when "EnableXmlText()" is not used, and it throws exception when it is.

The exception thrown is "XmlException: Value cannot be null."
I checked source code a bit and i can see that the "SomeInnerText" is actually parsed and is stored somewhere, however it is not getting assigned to the Text property of the ClassA class.

![image](https://user-images.githubusercontent.com/9079888/81308362-fb542c80-9081-11ea-86f2-31453ce51547.png)

Please let me know if you need more info, looking forward to your answer :)

**Comment by Mike-E-wins** [comment] 2020-05-07 15:15
Heya @Lakistein thanks for writing in.  Unfortunately `XmlTextAttribute` is not supported well with our API.  You can see more of this on #192 and #242.  It is also mentioned in our FAQ FWIW (I know I know who reads those?! 😅):

https://github.com/ExtendedXmlSerializer/home/wiki/FAQs#systemxmlserializer-vs-extendedxmlserializer

Unfortunately, I made things worse by _attempting_ to add support with the `EnableXmlText` extension method that you mention, but while it did fix one specific scenario it pretty much didn't do much for everything else. 😭

Really, I should deprecate that method call because it makes it seem that we support this feature when we really do not.  Or perhaps update the documentation to make it more obvious that this "feature" isn't really fleshed out as desired.  It was a bad attempt and it's causing more trouble than it's worth, unfortunately.

Sorry for the disappointing answer.  If someone wants to submit a PR to fix the issue, I would more than welcome it, however. 👍

**Comment by Lakistein** [comment] 2020-05-07 15:23
Hi @Mike-E-wins , thanks for the quick reply :)

I actually did read FAQ and few issues related to XmlText, but I was hoping that there is more to it :(

That being said, is there any other way to read "SomeInnerText" and store it in Text property ? Because I can still see it being parsed by the reader ?

**Comment by Mike-E-wins** [comment] 2020-05-07 15:52
Yeah, unfortunately, it is a good learning lesson for me personally in trying to please everyone.  Actually, I say that, but I feel I have done a pretty good job here. 
 But for some reason, `XmlText` has been a stickler in my side, doh.

As for workarounds, if you have non-EXS XML and want to serialize it into EXS and back, my recommendation would be to look into XSLT as that is what it is designed for.  You could also look into using a custom serializer, but that might end up being more trouble than it's worth.

I did try poking around with registering a custom `ISerializer<string>` for the property but the problem is that the `<Text ` element is already written at that point, so it is in an awkward state to simply write the current value.

So, XSLT is probably your best bet, unfortunately.  However, I will think about this some more, however, and update if any lightning strikes. 😁

**Comment by Mike-E-wins** [comment] 2020-06-09 12:41
Sounds like we've attended to this issue as much as we can.  `XmlText` isn't a fully-supported legacy feature and is captured as such in the documentation.  If you have any further questions/comments around this please do not hesitate to share and we can certainly revisit this in greater depth.  Hopefully, this issue will help others running into this problem in the future as well.  Closing this issue for now.

**Closed by Mike-E-wins** 2020-06-09 12:41 UTC
Labels: question
